# ==============================
# DATABASE (PostgreSQL - Render)
# ==============================
spring.datasource.url=jdbc:postgresql://dpg-d7i7ss67r5hc73c5n17g-a.virginia-postgres.render.com:5432/ap13?sslmode=require
spring.datasource.username=ap13_user
spring.datasource.password=xC6Dt60v8GKntbLTcbOZpL3cHnZPb5zO
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================
# JPA / HIBERNATE
# ==============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# ==============================
# CONNECTION POOL (IMPORTANT)
# ==============================
spring.datasource.hikari.initialization-fail-timeout=0
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5

# ==============================
# SERVER PORT (MANDATORY FOR RENDER)
# ==============================
server.port=${PORT:8080}