# 1. DATABASE CONNECTION
# We add a default 'none' or a dummy local URL so it doesn't crash during build
spring.datasource.url=${MYSQL_URL:jdbc:mysql://dpg-d7i7ss67r5hc73c5n17g-a/5432/ap13}
spring.datasource.username=${ap13_user}
spring.datasource.password=${xC6Dt60v8GKntbLTcbOZpL3cHnZPb5zO}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. HIBERNATE DIALECT (The Fix for your specific error)
# This line tells Hibernate exactly what language to speak without "asking" the DB
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# 3. RENDER PORT
server.port=${PORT:5432}

# 4. DEFER DATASOURCE (Add this line)
# This tells Spring NOT to crash if the DB isn't ready at the exact second of startup
spring.jpa.defer-datasource-initialization=true